apiVersion: v1
kind: ConfigMap
metadata:
  name: jaas-ldap
  namespace: rundeck
data:
  jaas-activedirectory.conf: |
    activedirectory {
        com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        providerUrl=""
        bindDn=""
        bindPassword=""
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn=""
        userRdnAttribute="sAMAccountName"
        userIdAttribute="sAMAccountName"
        userPasswordAttribute="unicodePwd"
        userObjectClass="user"
        roleBaseDn=""
        roleNameAttribute="cn"
        roleMemberAttribute="member"
        roleObjectClass="group"
        cacheDurationMillis="300000"
        reportStatistics="true";

      org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
        debug="true"
        hotReload="true"
        refreshInterval="60"
        file="/etc/rundeck/realm.properties";
    };
